import numpy as np
import re
import os
from math import pi
import sys
import h5py
from utils.eu2qu import eu2qu

def eu_txt_reader(txt_dir, unit='deg'):
    '''
    Reading euler angles from txt file generated by EMsoft
    and transfer to orientations

    Input
    ----------------------------
    txt_dir: dir of txt file containing Euler angles
    unit: 'deg' or 'rad'

    Output
    ----------------------------
    orientations: ndarray, n*4
    '''
    assert os.path.exists(txt_dir), "txt file {} does not exist.".format(txt_dir) 
    p = re.compile(r'(\d+\.?\d*e-\d+|\d+\.?\d*)')

    def read():
        f = open(txt_dir, 'r')
        if unit == 'deg':
            for i in f.readlines():
                numbers = p.findall(i)
                numbers = [float(j) for j in numbers]
                if len(numbers) == 3:
                    yield eu2qu(np.array(numbers)*pi/180).reshape((1,4))
                else:
                    print(i)
        elif unit == 'rad':
            for i in f.readlines():
                numbers = p.findall(i)
                numbers = [float(j) for j in numbers]
                if len(numbers) == 3:
                    yield eu2qu(np.array(numbers)).reshape((1,4))
                else:
                    print(i)
        f.close()
    
    orientations = np.concatenate([i for i in read()], axis=0)
    
    print('# of orientations generated: %d' % orientations.shape[0])
    return orientations

if __name__ == '__main__':
    pass
